config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :users, :controllers => { :registrations => "registrations" }
  root 'welcome#index'

  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validate :picture_size

  private
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  attr_accessor :card_number, :card_cvv, :card_expires_month, :card_expires_year
    belongs_to :user

    def self.month_options
        Date::MONTHNAMES.compact.each_with_index.map { |name, i| ["#{i+1} - #{name}", i+1]}
    end

    def self.year_options
        (Date.today.year..(Date.today.year+10)).to_a
    end

    def process_payment
        customer = Stripe::Customer.create email: email, card: token
        Stripe::Charge.create customer: customer.id, amount: 1000, description: "Premium", currency: "usd"
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :payment
  has_many :images
  accepts_nested_attributes_for :payment
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  pay_customer stripe_attributes: :stripe_attributes

  def stripe_attributes(pay_customer)
    {
      address: {
        city: pay_customer.owner.city,
        country: pay_customer.owner.country
      },
      metadata: {
        pay_customer_id: pay_customer.id,
        user_id: id # or pay_customer.owner_id
      }
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_user_paid?

  def show
    current_user.set_payment_processor :stripe
    current_user.payment_processor.customer

    @checkout_session = current_user
                        .payment_processor
                        .checkout(
                          mode: 'payment',
                          line_items: 'price_1PRRjLI4Zyhf3cOmJl2SSnPC',
                          success_url: checkout_success_url
                            )
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @line_items = Stripe::Checkout::Session.list_line_items(params[:session_id])
    current_user.paid = true
    current_user.save!
  end

  private
  def is_user_paid?
    if current_user.paid?
      flash[:alert] = "You have already paid."
      redirect_to root_path
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy!

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:name_string, :picture).merge(user: current_user)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
      build_resource(sign_up_params)
      resource.class.transaction do
          resource.save
          yield resource if block_given?
          if resource.persisted?
              @payment = Payment.new({ email: params["user"]["email"], token: params[:payment]["token"],
              user_id: resource.id })
          flash[:error] = "Please check registration errors" unless @payment.valid?
          begin
              @payment.process_payment
              @payment.save
          rescue Exception => e
              flash[:alert] = e.message

              resource.destroy
              puts "Payment failed"
              render :new and return
          end
          if resource.active_for_authentication?
              set_flash_message! :notice, :signed_up if is_flashing_format?
              sign_up(resource_name, resource)
              respond_with resource, location: after_sign_up_path_for(resource)
            else
              set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
              expire_data_after_sign_in!
              respond_with resource, location: after_inactive_sign_up_path_for(resource)
          end
      else
          clean_up_passwords resource
          set_minimum_password_length
          respond_with resource
      end
  end
end
protected
def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up).push(:payment)
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/checkouts/show.html.erb
<h1>Checkout!</h1>
<div class="row">
  <div class="col-lg-12 align-items-center justify-content-center">
 <h3 class="card-title">Premium Plan</h3>
        <div class="features">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
          </ul>
        </div>
        <p class="card-text">One time Price: $10</p>


<%= render partial: 'pay/stripe/checkout_button', locals: {
    session: @checkout_session,
    title: "Pay now"
} %>
  </div>
</div>

app/views/checkouts/success.html.erb
<h1>Succcess</h1>
<p>You just payed for my thing!</p>
<h2>Total amount $<%= @session.amount_total.to_f / 100 %> </h2>
<br>
<% @line_items.each do |item|%>
    <h3><%= item.description %></h3>





<% end %>

app/views/images/_form.html.erb
<%= form_for @image, :html => { multipart: true, :class => "form-horizontal image" } do |f| %>

  <% if @image.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name_string, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group mt-3">
    <%= f.label :current_image, :class => 'control-label col-lg-2' %>
    <%= image_tag(@image.picture.url, width: "250") if @image.picture? %>
    <div class="col-lg-10 mt-3">
      <%= "Change Image:" if @image.picture? %>
      <p></p>
      <%= f.file_field :picture, accept: "image/jpeg,image/jpg,image/gif,image/png" %>
    </div>
    <%=f.error_span(:picture) %>
  </div>  

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10 mt-3">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
          $("#image_picture").bind("change", function() {
            var size_in_megabytes = this.files[0].size/1024/1024;
            if (size_in_megabytes > 5) {
              alert("Maximum file size is 5MB.");
            }
          });
</script>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <p>
    <strong>Name string:</strong>
    <%= image.name_string %>
  </p>

  <p>
    <strong>Picture:</strong>
    <%= image.picture %>
  </p>

  <p>
    <strong>User:</strong>
    <%= image.user_id %>
  </p>

</div>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% if !current_user.paid%>
<h4 class="upgrade-text"><b><i>Upgrade now to edit and add photos</i></b></h4>
<%end%>
<table class="table table-striped">
  <thead>
    <tr>      
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.name_string, image_path(image), class: "links"%></td>
        <td><%= image_tag image.picture.url, height: "300" %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      image_path(image), :class => 'btn btn-default btn-xs' %>
          <% if current_user.paid %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_image_path(image), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.delete', :default => t("helpers.links.destroy")),
                      image_path(image),
                      :data => {"turbo-method": :delete, :turbo_confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
                      <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user.paid %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_image_path,
            :class => 'btn btn-primary' %>
            <%end %>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name_string) %>:</strong></dt>
  <dd><%= @image.name_string %></dd>
    <dt></dt>
    <dd><%= image_tag(@image.picture.url, width: "500") if @image.picture? %></dd>  
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              images_path, :class => 'btn btn-default'  %>
<% if current_user.paid%>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_image_path(@image), :class => 'btn btn-default' %>
  <%= link_to t('.delete', :default => t("helpers.links.destroy")),
                image_path(@image),
                :data => {"turbo-method": :delete, :turbo_confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
    </head>

  <body>
    <%# nav %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <%= link_to "PhotoApp", root_path, class: "navbar-brand", id: "logo" %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li><%= link_to "Images", images_path, class: "nav-link" %></li>  
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to edit_user_registration_path, class: "dropdown-item" do %> 
                        Edit profile
                      <% end %>
                  </li>
            </ul>
          </ul>
          <% if current_user %>
            <ul class="navbar-nav ms-auto">
            <li class="nav-item user-name">
              <%= current_user.email %>
            </li>
            <% if !current_user.paid %>
            <li class="nav-item">
              <%= link_to 'Upgrade Now!', checkout_path, class: 'btn btn-success logout-button'%>
            </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-secondary logout-button', data: {turbo_method: :delete} %>
            </li>
            <% else %>
            <ul class="nav-item ms-auto">
              <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-secondary logout-button', data: {turbo_method: :get} %>
            </ul>
            </ul>
            <% end %>
        </div>
      </div>
    </nav>

        <div class="container">
      <div class="row">
        <div class="col-lg-12">
            <%= render 'layouts/messages' %>
          <%= yield %>
          
        </div>
      </div>
    </div> 
  </body>
</html>

app/views/welcome/index.html.erb
<% if current_user %>
  <div class="jumbotron text-center">
    <h2>Welcome to the Photo Management App.</h2>
  </div>

  <div class="row">
  <div class="col-sm-3 mx-auto">
    <% if !current_user.paid?%>
    <div class="card mx-auto">
      <div class="card-body mx-auto">
        <h5 class="card-title mx-auto">Premium Plan</h5>
        <div class="features mx-auto">
          <ul>
            <li>Unlimited Image Uploads</li>
            <li>Responsive design</li>
            <li>Access anywhere</li>
          </ul>
        </div>
        <p class="card-text">One time payment: $10</p>
          <%= link_to 'Checkout', checkout_path, class: 'btn btn-success sign-up' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>